# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Modem3GSwitcher(object):
    def setupUi(self, Modem3GSwitcher):
        Modem3GSwitcher.setObjectName("Modem3GSwitcher")
        Modem3GSwitcher.resize(572, 261)
        self.groupBox = QtWidgets.QGroupBox(Modem3GSwitcher)
        self.groupBox.setGeometry(QtCore.QRect(340, 0, 231, 291))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border: none; background: transparent;")
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 41, 11))
        self.label_4.setObjectName("label_4")
        self.manu_label = QtWidgets.QLabel(self.groupBox)
        self.manu_label.setGeometry(QtCore.QRect(10, 100, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manu_label.setFont(font)
        self.manu_label.setText("")
        self.manu_label.setObjectName("manu_label")
        self.model_label = QtWidgets.QLabel(self.groupBox)
        self.model_label.setGeometry(QtCore.QRect(10, 150, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.model_label.setFont(font)
        self.model_label.setText("")
        self.model_label.setObjectName("model_label")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 41, 11))
        self.label_6.setObjectName("label_6")
        self.firmware_label = QtWidgets.QLabel(self.groupBox)
        self.firmware_label.setGeometry(QtCore.QRect(10, 190, 211, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firmware_label.setFont(font)
        self.firmware_label.setText("")
        self.firmware_label.setObjectName("firmware_label")
        self.imei_label = QtWidgets.QLabel(self.groupBox)
        self.imei_label.setGeometry(QtCore.QRect(10, 230, 211, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.imei_label.setFont(font)
        self.imei_label.setText("")
        self.imei_label.setObjectName("imei_label")
        self.status_label = QtWidgets.QLabel(self.groupBox)
        self.status_label.setGeometry(QtCore.QRect(0, 30, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.applyButton = QtWidgets.QDialogButtonBox(Modem3GSwitcher)
        self.applyButton.setEnabled(True)
        self.applyButton.setGeometry(QtCore.QRect(180, 170, 131, 32))
        self.applyButton.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.applyButton.setCenterButtons(True)
        self.applyButton.setObjectName("applyButton")
        self.label = QtWidgets.QLabel(Modem3GSwitcher)
        self.label.setGeometry(QtCore.QRect(90, 40, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Modem3GSwitcher)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_2.setObjectName("label_2")
        self.mode = QtWidgets.QComboBox(Modem3GSwitcher)
        self.mode.setGeometry(QtCore.QRect(20, 170, 171, 31))
        self.mode.setEditable(False)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.checkpushButton = QtWidgets.QPushButton(Modem3GSwitcher)
        self.checkpushButton.setGeometry(QtCore.QRect(200, 60, 51, 31))
        self.checkpushButton.setObjectName("checkpushButton")
        self.Port = QtWidgets.QLineEdit(Modem3GSwitcher)
        self.Port.setGeometry(QtCore.QRect(90, 60, 111, 31))
        self.Port.setObjectName("Port")
        self.errLabel = QtWidgets.QLabel(Modem3GSwitcher)
        self.errLabel.setGeometry(QtCore.QRect(9, 99, 321, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.errLabel.setFont(font)
        self.errLabel.setStyleSheet("color: red;")
        self.errLabel.setText("")
        self.errLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errLabel.setWordWrap(True)
        self.errLabel.setObjectName("errLabel")
        self.label_7 = QtWidgets.QLabel(Modem3GSwitcher)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Modem3GSwitcher)
        QtCore.QMetaObject.connectSlotsByName(Modem3GSwitcher)

    def retranslateUi(self, Modem3GSwitcher):
        _translate = QtCore.QCoreApplication.translate
        Modem3GSwitcher.setWindowTitle(_translate("Modem3GSwitcher", "Huawei Modem 3G Switcher"))
        self.groupBox.setTitle(_translate("Modem3GSwitcher", "Device Info:"))
        self.label_3.setText(_translate("Modem3GSwitcher", "Manufacturer:"))
        self.label_4.setText(_translate("Modem3GSwitcher", "Model:"))
        self.label_5.setText(_translate("Modem3GSwitcher", "Firmware Version:"))
        self.label_6.setText(_translate("Modem3GSwitcher", "IMEI:"))
        self.label.setText(_translate("Modem3GSwitcher", "USB Port Address"))
        self.label_2.setText(_translate("Modem3GSwitcher", "Network Mode"))
        self.mode.setItemText(0, _translate("Modem3GSwitcher", "2G/EDGE Preferred"))
        self.mode.setItemText(1, _translate("Modem3GSwitcher", "3G/WCDMA Preferred"))
        self.mode.setItemText(2, _translate("Modem3GSwitcher", "2G/EDGE Only"))
        self.mode.setItemText(3, _translate("Modem3GSwitcher", "3G/WCDMA Only"))
        self.checkpushButton.setText(_translate("Modem3GSwitcher", "Check"))
        self.Port.setText(_translate("Modem3GSwitcher", "/dev/tty0"))
        self.label_7.setText(_translate("Modem3GSwitcher", "Report bugs: i@donjajo.com"))

